name: simple flow
on: push
jobs: 
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: step 1 -some informative name
        uses: actions/checkout@v2
      - name: step 2 -
        run: ls -a

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: step 1
        uses: actions/checkout@v2
      - name: step 2
        run: pwd
      
      
